version: "3.8"
services:
    mongodb:
        image: mongo:3.6
        hostname: mongodb
        container_name: db-mongo
        ports:
            - "27017:27017"
        command: --bind_ip_all --smallfiles
        volumes:
            - mongodb:/data
        networks:
            - default

    mysql-db:
        restart: always
        image: mysql
        hostname: mysql-db
        container_name: db-mysql
        expose:
            - "3306"
        ports:
            - "3306:3306"
        networks:
            - default
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
            - "MYSQL_ROOT_HOST=%"
        volumes:
            - mysql-db:/var/lib/mysql

    cygnus:
        image: fiware/cygnus-ngsi:latest
        hostname: cygnus
        container_name: fiware-cygnus
        networks:
            - default
        depends_on:
            - mysql-db
        expose:
            - "5080"
        ports:
            - "5050:5050"
            - "5080:5080"
        environment:
            - "CYGNUS_MYSQL_HOST=mysql-db"
            - "CYGNUS_MYSQL_PORT=3306"
            - "CYGNUS_MYSQL_USER=root"
            - "CYGNUS_MYSQL_PASS=123"
            - "CYGNUS_MYSQL_SERVICE_PORT=5050"
            - "CYGNUS_LOG_LEVEL=DEBUG"
            - "CYGNUS_API_PORT=5080"
            - "CYGNUS_SERVICE_PORT=5050"

    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - mysql-db
            - mongodb
            - orion
        ports:
            - "3000:3000"
        environment:
            - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel"
            - "GF_INSTALL_PLUGINS=https://github.com/cloudspout/cloudspout-button-panel/releases/download/7.0.2/cloudspout-button-panel.zip;cloudspout-button-panel"
        volumes:
            - grafana:/var/lib/grafana
        networks:
            - default

    orion:
        image: fiware/orion:latest
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongodb
        expose:
            - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongodb -logLevel DEBUG
        healthcheck:
            test: curl --fail -s http://orion:1026/version || exit 1
        networks:
            - default

    iot-agent-json:
        image: fiware/iotagent-json
        hostname: iot-agent-json
        depends_on:
            - mongodb
        expose:
            - "4041"
            - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_MONGO_HOST=mongodb"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-json"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_PROVIDER_URL=http://iot-agent-json:4041"
        networks:
            - default

    irrigation_recommendation:
        build:
            context: ./irrigation_recommendation
        image: irrigation_recommendation:test
        container_name: irrigation_recommendation
        networks:
            - default
        depends_on:
            - orion
            - mysql-db
            - cygnus

    weatherHandler:
        build:
            context: ./weather_handler
        image: weather_handler:test
        container_name: weather_handler
        networks:
            - default
        depends_on:
            - orion

    OpcUAServer:
        hostname: OpcUAServer
        build:
            context: ./OpcUAServer
        image: opc_ua_server:test
        container_name: opc_ua_server
        networks:
            - default
        ports:
            - "5001:5001"
            - "4840:4840"
        
    data_model:
        build:
            context: ./data_model
        image: data_model:test
        container_name: data_model
        networks:
            - default
        depends_on:
            - orion

    probe:
        build:
            context: ./probe
        image: probe:test
        container_name: probe
        networks:
            - default
        depends_on:
            - orion
            - iot-agent-json
       
    iot-agent-opcua:
        hostname: iot-agent-opcua
        image: iotagent4fiware/iotagent-opcua:v1.3.7
        networks:
            - default
        ports:
            - "4001:4001"
            - "4081:8080"
        depends_on:
            - OpcUAServer
            - mongodb
            - orion
        volumes:
            - ./iotAgentOpcUa/AGECONF:/opt/iotagent-opcua/conf
            - ./iotAgentOpcUa/certificates:/opt/iotagent-opcua/certificates
        command: /usr/bin/tail -f /var/log/lastlog

networks:
  default:

volumes:
    mongodb: ~
    grafana: ~
    mysql-db: ~
