version: "3.8"
services:
    mongodb:
        image: mongo:3.6
        hostname: mongodb
        container_name: db-mongo
        ports:
            - "27017:27017"
        command: --bind_ip_all --smallfiles
        volumes:
            - mongodb:/data
        networks:
            - default

    mysql-db:
        restart: always
        image: mysql:5.7
        hostname: mysql-db
        container_name: db-mysql
        expose:
            - "3306"
        ports:
            - "3306:3306"
        networks:
            - default
        environment:
            - "MYSQL_ROOT_PASSWORD=123"
            - "MYSQL_ROOT_HOST=%"
        volumes:
            - mysql-db:/var/lib/mysql

    cygnus:
        image: fiware/cygnus-ngsi:latest
        hostname: cygnus
        container_name: fiware-cygnus
        networks:
            - default
        depends_on:
            - mysql-db
        expose:
            - "5080"
        ports:
            - "5050:5050"
            - "5080:5080"
        environment:
            - "CYGNUS_MYSQL_HOST=mysql-db"
            - "CYGNUS_MYSQL_PORT=3306"
            - "CYGNUS_MYSQL_USER=root"
            - "CYGNUS_MYSQL_PASS=123"
            - "CYGNUS_MYSQL_SERVICE_PORT=5050"
            - "CYGNUS_LOG_LEVEL=DEBUG"
            - "CYGNUS_API_PORT=5080"
            - "CYGNUS_SERVICE_PORT=5050"

    grafana:
        image: grafana/grafana
        container_name: grafana
        depends_on:
            - mysql-db
            - mongodb
            - orion
        ports:
            - "3000:3000"
        environment:
            - "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel"
        volumes:
            - grafana:/var/lib/grafana
        networks:
            - default

    orion:
        image: fiware/orion:latest
        hostname: orion
        container_name: fiware-orion
        depends_on:
            - mongodb
        expose:
            - "1026"
        ports:
            - "1026:1026"
        command: -dbhost mongodb -logLevel DEBUG
        healthcheck:
            test: curl --fail -s http://orion:1026/version || exit 1
        networks:
            - default

    iot-agent-ul:
        image: fiware/iotagent-ul:1.8.0
        hostname: iot-agent-ul
        depends_on:
            - mongodb
        ports:
            - "4042:4042"
            - "7897:7897"
        environment:
            - IOTA_CB_HOST=orion # name of the context broker to update context
            - IOTA_CB_PORT=1026 # port the context broker listens on to update context
            - IOTA_NORTH_PORT=4042
            - IOTA_REGISTRY_TYPE=mongodb #Whether to hold IoT device info in memory or in a database
            - IOTA_LOG_LEVEL=DEBUG # The log level of the IoT Agent
            - IOTA_TIMESTAMP=true # Supply timestamp information with each measurement
            - IOTA_CB_NGSI_VERSION=v2 # use NGSIv2 when sending updates for active attributes
            - IOTA_AUTOCAST=true # Ensure Ultralight number values are read as numbers not strings
            - IOTA_MONGO_HOST=mongodb # The host name of MongoDB
            - IOTA_MONGO_PORT=27017 # The port mongoDB is listening on
            - IOTA_MONGO_DB=iotagentul # The name of the database used in mongoDB
            - IOTA_HTTP_PORT=7897 # The port used for device traffic over HTTP
            - IOTA_PROVIDER_URL=http://iot-agent-ul:4042
        healthcheck:
            test: curl --fail -s http://iot-agent-ul:4042/iot/about || exit 1
        networks:
            - default

    iot-agent-json:
        image: fiware/iotagent-json
        hostname: iot-agent-json
        depends_on:
            - mongodb
        expose:
            - "4041"
            - "7896"
        ports:
            - "4041:4041"
            - "7896:7896"
        environment:
            - "IOTA_CB_HOST=orion"
            - "IOTA_CB_PORT=1026"
            - "IOTA_NORTH_PORT=4041"
            - "IOTA_REGISTRY_TYPE=mongodb"
            - "IOTA_MONGO_HOST=mongodb"
            - "IOTA_MONGO_PORT=27017"
            - "IOTA_MONGO_DB=iotagent-json"
            - "IOTA_HTTP_PORT=7896"
            - "IOTA_PROVIDER_URL=http://iot-agent-json:4041"
        networks:
            - default

    fuzzyneeds:
        build:
            context: ./fuzzyneeds
        image: fuzzyneeds:test
        container_name: fuzzyneeds 
        networks:
            - default

    OpcUAServer:
        hostname: OpcUAServer
        build:
            context: ./OpcUAServer
        image: opc_ua_server:test
        container_name: opc_ua_server
        networks:
            - default
        ports:
            - "5001:5001"
            - "4840:4840"
       
    iot-agent-opcua:
        hostname: iot-agent-opcua
        image: iotagent4fiware/iotagent-opcua:latest
        networks:
            - default
        ports:
            - "4003:4003"
            - "4081:8080"
        depends_on:
            - OpcUAServer
            - mongodb
            - orion
        volumes:
            - ./AGECONF:/opt/iotagent-opcua/conf
            - ./certificates:/opt/iotagent-opcua/certificates
        command: /usr/bin/tail -f /var/log/lastlog

networks:
  default:

volumes:
    mongodb: ~
    grafana: ~
    mysql-db: ~
